---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Update apt-get repo and cache
    apt:  update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
  - name: install packages
    package:
      name: 
       - htop
       - tmux
       - vim-nox
       - zsh
       - fonts-powerline
  - name: download oh-my-zsh
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /home/vyas0/zsh-installer.sh
  - name: Execute the zsh-installer.sh
    become: true
    shell: /home/vyas0/zsh-installer.sh
  - name: Remove the zsh-installer.sh
    become: true
    file: path=/home/vyas0/zsh-installer.sh state=absent
  - name: change user shell to zsh 
    become: yes
    user:
      name: vyas0
      shell: /bin/zsh
  
  # - name: copy .bashrc file
  #   copy:
  #     src: files/bashrc
  #     dest: /home/vyas0/.bashrc
  #     owner: vyas0
  #     group: vyas0
  # - name: copy .zshrc file
  #   copy:
  #     src: files/zshrc
  #     dest: /home/vyas0/.zshrc
  #     owner: vyas0
  #     group: vyas0
  - name: add ansible user
    user:
      name: ansibleusr
      system: yes
  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansibleusr
      dest: /etc/sudoers.d/ansibleusr
      owner: root
      group: root
      mode: 0440
  - name: add ansible-pull cron job
    cron: 
      name: ansible auto-provision
      user: ansibleusr
      special_time: hourly
      job: ansible-pull -o -U https://github.com/vyas0189/ansible_local.git 